### ISSUE TITLE
[BUG] *Summary of bug*

### ISSUE THREAD

**Issue by paseman** [MilesCranmer/PySR#168]
**Describe the bug**
Can't install
Did 
conda install -c conda-forge pysr
python -c 'import pysr; pysr.install()'
got
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/katherinepaseman/anaconda3/lib/python3.8/site-packages/pysr/__init__.py", line 12, in <module>
    from .export_jax import sympy2jax
  File "/Users/katherinepaseman/anaconda3/lib/python3.8/site-packages/pysr/export_jax.py", line 52, in <module>
    sympy.core.numbers.Half: "(lambda: 0.5)",
AttributeError: module 'sympy.core.core' has no attribute 'numbers'

**Version (please include the following information):**
- OS: [e.g. macOS] - Running MacOS versions 13.4
- Julia version [Run `julia --version` in the terminal]
- Python version [Run `python --version` in the terminal]
- PySR version [e.g. 0.6.0]
- Does the bug still appear with the latest version of PySR? - yes

**Configuration**
- What are your PySR settings?
- What dataset are you running on?
- If possible, please share a minimal code example that produces the error.

**Error message**
Add the error message here, or whatever other information would be useful for debugging.

If the error is "Couldn't find equation file...", this error indicates something
went wrong with the backend. Please scroll up and copy
the output of Julia, rather than the output of python.

**Additional context**

**Comment by MilesCranmer** [comment]
Thanks. It looks like the `sympy` version might be a bit older. Could you try `conda update sympy`?

**Comment by paseman** [comment]
Thanks for the prompt reply.
Did conda update sympy
then
python -c 'import pysr; pysr.install()' 
Systems has been stuck about 15 minutes after printing out
(base) katherinepaseman@Bills-MacBook-Pro-3 Pysr % python -c 'import pysr; pysr.install()'             
[ Info: Julia version info
Julia Version 1.6.5
Commit 9058264a69* (2021-12-19 12:30 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  uname: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz: 
                 speed         user         nice          sys         idle          irq
       #1-16  2400 MHz      63120 s          0 s      45605 s    2510451 s          0 s
       
  Memory: 64.0 GB (30091.30859375 MB free)
  Uptime: 16370.0 sec
  Load Avg:  7.0849609375  3.90478515625  2.82763671875
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH_BACKUP = 
  JULIA_PROJECT_BACKUP = 
  JULIA_LOAD_PATH_BACKUP = 
  JULIA_DEPOT_PATH = /Users/katherinepaseman/anaconda3/share/julia:
  JULIA_SSL_CA_ROOTS_PATH_BACKUP = 
  JULIA_SSL_CA_ROOTS_PATH = /Users/katherinepaseman/anaconda3/ssl/cacert.pem
  XPC_FLAGS = 0x0
  TERM = xterm-256color
  HOME = /Users/katherinepaseman
  PATH = /Users/katherinepaseman/anaconda3/bin:/Users/katherinepaseman/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/git/bin
  PYTHONPATH = /Users/katherinepaseman/Documents/projects/py:/Users/katherinepaseman/Documents/projects/py/Analyst:
  JULIA_DEPOT_PATH_BACKUP = 
  JULIA_LOAD_PATH_BACKUP = 
  JULIA_DEPOT_PATH = /Users/katherinepaseman/anaconda3/share/julia:
  JULIA_SSL_CA_ROOTS_PATH_BACKUP = 
  JULIA_SSL_CA_ROOTS_PATH = /Users/katherinepaseman/anaconda3/ssl/cacert.pem
[ Info: Julia executable: /Users/katherinepaseman/anaconda3/bin/julia
[ Info: Trying to import PyCall...
┌ Error: `import PyCall` failed
│   exception =
│    ArgumentError: Package PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] is required but does not seem to be installed:
│     - Run `Pkg.instantiate()` to install all recorded dependencies.
│    
│    Stacktrace:
│     [1] _require(pkg::Base.PkgId)
│       @ Base ./loading.jl:1012
│     [2] require(uuidkey::Base.PkgId)
│       @ Base ./loading.jl:936
│     [3] top-level scope
│       @ ~/anaconda3/lib/python3.8/site-packages/julia/install.jl:36
│     [4] include(mod::Module, _path::String)
│       @ Base ./Base.jl:384
│     [5] exec_options(opts::Base.JLOptions)
│       @ Base ./client.jl:285
│     [6] _start()
│       @ Base ./client.jl:485
└ @ Main ~/anaconda3/lib/python3.8/site-packages/julia/install.jl:38
[ Info: Installing PyCall...
  Installing known registries into `~/anaconda3/share/julia`
┌ Error: curl_multi_socket_action: 8
└ @ Downloads.Curl /Users/runner/miniforge3/conda-bld/julia_1641439054055/work/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
