### ISSUE TITLE
PySR on the cluster - not working

### ISSUE THREAD

**Issue by praksovar** [MilesCranmer/PySR#289]
Hello Miles,
thank you for you excelent work. I am interested in searching SR models in many fields of my research and in the past I used Eureqa (https://link.springer.com/article/10.1007/s10710-010-9124-z). Recently, I use your PySR (e.g. https://www.mdpi.com/2075-1680/11/9/463). I read your tips for the running PySR on the cluster and I tried it also on our cluster Barbora (https://www.it4i.cz/en) BUT there are many errors:
1. Permission denied for: .julia/environments/v1.8/Project.toml - solved by export JULIA_DEPOT_PATH,JULIA_PROJECT and JULIA_LOAD_PATH to the local dir in scratch
2. I couldn't run: pysr.install() from Python - solved by installing manualy directly in Julia by import Pkg; Pkg.add("SymbolicRegression") 
3. Now, I got this error which I couldn't resolve (I don't have any experiencies with Julia):

Error launching workers
ErrorException("")
Activating environment on workers.
Importing installed module on workers...Finished!
Testing module on workers...Finished!
Testing entire pipeline on workers...Finished!
Traceback (most recent call last):
  File "/home/myname/myscript.py", line 49, in <module>
    model.fit(X, y)
  File "/apps/all/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/pysr/sr.py", line 1834, in fit
    self._run(X, y, mutated_params, weights=weights, seed=seed)
  File "/apps/all/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/pysr/sr.py", line 1694, in _run
    self.raw_julia_state_ = SymbolicRegression.EquationSearch(
RuntimeError: <PyCall.jlwrap (in a Julia function called from Python)
JULIA: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer

Please, do you have any tips to solve this error? What am I doing wrong? 
Thank you in advance!
Best regards,
Renata

Version:
OS: Red Hat Enterprise Linux 8.4 (Ootpa)
Julia 1.8.5
Python 3.10.8
PySR 0.12.1

I used this option settings - inspired by your advice:
model = PySRRegressor(
    niterations=500000, 
    population_size=108,
    binary_operators=["+", "*","/","^","-"],
    unary_operators=["abs","cos","log","exp","sin"],
    loss='L1DistLoss()',
    procs=36,cluster_manager='pbs',
    ncyclesperiteration=5000,turbo=True,
    maxdepth=7,parsimony=0.0001,weight_optimize=0.001,adaptive_parsimony_scaling=1000,
    nested_constraints={"sin": {"sin": 0, "cos": 0}, "cos": {"sin": 0, "cos": 0}}
    )

**Comment by MilesCranmer** [comment]
Hi @praksovar,

Everything looks good to me in your options.

1. Can you share the full error message? If it is long perhaps you could put it in a gist.github.com?
2. Is `procs=36` the same number of cores over your entire allocation? Or is it the number of cores per node? (It should be # of cores over entire allocation. i.e., num_nodes * num_cores_per_node). 
3. How are you launching this script - from the head node, or once per node? (It should just be launched from the head node; Julia will be able to create workers across the allocation)

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Hi @praksovar,

Just wanted to ping you on this. Please provide more details if possible so I can help fix it.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Hi @praksovar,

Sorry for the late reply. The issue is that you are using `multithreading=True`. You need to have `multithreading=False` for multiprocessing mode to be enabled.

Likewise in the pure Julia mode, you need to use `parallelism=:multiprocessing, addprocs_function=addprocs_pbs`, rather than `parallelism=:multithreading`. 

Cheers,
Miles
