### ISSUE TITLE
[BUG]: PySR currently incompatible with Python 3.12

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#451]
Until the PR at https://github.com/JuliaPy/pyjulia/pull/538 is merged, PySR is currently incompatible with Python 3.12. This is due to a breaking change in the way Python allowed PyJulia to overload the import function (like `from julia import SymbolicRegression`). It seems to be an easy patch though, luckily.

**Comment by PaulGersberg** [comment]
Also incompatible with 3.11.6
`python -m pysr install 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\pysr\__main__.py", line 4, in <module>
    _cli(prog_name="pysr")
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\pysr\julia_helpers.py", line 283, in _julia_version_assertion
    if not is_julia_version_greater_eq(version=(1, 6, 0)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\pysr\julia_helpers.py", line 147, in is_julia_version_greater_eq
    juliainfo = _load_juliainfo()
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\pysr\julia_helpers.py", line 25, in _load_juliainfo
    juliainfo = JuliaInfo.load(julia="julia")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pgersber\AppData\Local\miniconda3\Lib\site-packages\julia\juliainfo.py", line 87, in load
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status 1.`

**Comment by MilesCranmer** [comment]
Hi @PaulGersberg,
That looks like a different issue. The 3.12 incompatibility is specifically related to how imports work in PyJulia.
Cheers,
Miles

**Comment by MilesCranmer** [comment]
Fixed with PyJulia 0.6.2: https://github.com/JuliaPy/pyjulia/releases/tag/v0.6.2

**Comment by MilesCranmer** [comment]
Fixed by #535 (for good this time)
