### ISSUE TITLE
[BUG]: model.fit works but there's an error at the end in parse_expr

### ISSUE THREAD

**Issue by SrGonao** [MilesCranmer/PySR#627]
### What happened?

When training a model using:
`model = PySRRegressor(niterations=1000,maxsize=30,maxdepth=15,ncycles_per_iteration=100,populations=10,binary_operators=["+", "*","/"],
    unary_operators=[
        "exp",
        "inv(x) = 1/x",
        "square",
        "cube",
        "sqrt",
        "log",
        "logistic(x) = 1 / (1 + exp(-x))", 
        # ^ Custom operator (julia syntax)
    ],
    extra_sympy_mappings={"inv": lambda x: 1 / x,"logistic": lambda x: 1.0 / (1.0 + np.exp(-x))},)
`
it correctly finds and expression but then there is an error when trying to convert to an expression `loop of ufunc does not support argument 0 of type Mul which has no callable exp method`.

I've tried different ways to introduce new mappings but have had no sucess. I would have expected that the error would be thrown out at the start of fitting and not at the end.

### Version

0.18.1

### Operating System

Linux

### Package Manager

pip

### Interface

Jupyter Notebook

### Relevant log output

```shell
{
	"name": "TypeError",
	"message": "loop of ufunc does not support argument 0 of type Mul which has no callable exp method",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Error from parse_expr with transformed code: \"logistic (x0 )+(((x1 +-Float ('1.3587815' ))*square (x0 ))*Float ('0.00025213166' ))\"

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[9], line 1
----> 1 model.fit(x, y)

File ~/.local/lib/python3.8/site-packages/pysr/sr.py:1929, in PySRRegressor.fit(self, X, y, Xresampled, weights, variable_names, X_units, y_units)
   1926     self._checkpoint()
   1928 # Perform the search:
-> 1929 self._run(X, y, mutated_params, weights=weights, seed=seed)
   1931 # Then, after fit, we save again, so the pickle file contains
   1932 # the equations:
   1933 if not self.temp_equation_file:

File ~/.local/lib/python3.8/site-packages/pysr/sr.py:1779, in PySRRegressor._run(self, X, y, mutated_params, weights, seed)
   1776 self.julia_state_stream_ = jl_serialize(out)
   1778 # Set attributes
-> 1779 self.equations_ = self.get_hof()
   1781 if self.delete_tempfiles:
   1782     shutil.rmtree(self.tempdir_)

File ~/.local/lib/python3.8/site-packages/pysr/sr.py:2249, in PySRRegressor.get_hof(self)
   2246     torch_format = []
   2248 for _, eqn_row in output.iterrows():
-> 2249     eqn = pysr2sympy(
   2250         eqn_row[\"equation\"],
   2251         feature_names_in=self.feature_names_in_,
   2252         extra_sympy_mappings=self.extra_sympy_mappings,
   2253     )
   2254     sympy_format.append(eqn)
   2256     # NumPy:

File ~/.local/lib/python3.8/site-packages/pysr/export_sympy.py:86, in pysr2sympy(equation, feature_names_in, extra_sympy_mappings)
     79     feature_names_in = []
     80 local_sympy_mappings = {
     81     **create_sympy_symbols_map(feature_names_in),
     82     **(extra_sympy_mappings if extra_sympy_mappings is not None else {}),
     83     **sympy_mappings,
     84 }
---> 86 return sympify(equation, locals=local_sympy_mappings)

File ~/.local/lib/python3.8/site-packages/sympy/core/sympify.py:496, in sympify(a, locals, convert_xor, strict, rational, evaluate)
    494 try:
    495     a = a.replace('\
', '')
--> 496     expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
    497 except (TokenError, SyntaxError) as exc:
    498     raise SympifyError('could not parse %r' % a, exc)

File ~/.local/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py:1101, in parse_expr(s, local_dict, transformations, global_dict, evaluate)
   1099 for i in local_dict.pop(null, ()):
   1100     local_dict[i] = null
-> 1101 raise e from ValueError(f\"Error from parse_expr with transformed code: {code!r}\")

File ~/.local/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py:1092, in parse_expr(s, local_dict, transformations, global_dict, evaluate)
   1089     code = compile(evaluateFalse(code), '<string>', 'eval')
   1091 try:
-> 1092     rv = eval_expr(code, local_dict, global_dict)
   1093     # restore neutral definitions for names
   1094     for i in local_dict.pop(null, ()):

File ~/.local/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py:907, in eval_expr(code, local_dict, global_dict)
    901 def eval_expr(code, local_dict: DICT, global_dict: DICT):
    902     \"\"\"
    903     Evaluate Python code generated by ``stringify_expr``.
    904 
    905     Generally, ``parse_expr`` should be used.
    906     \"\"\"
--> 907     expr = eval(
    908         code, global_dict, local_dict)  # take local objects in preference
    909     return expr

File <string>:1

Cell In[8], line 12, in <lambda>(x)
      1 model = PySRRegressor(niterations=1000,maxsize=30,maxdepth=15,ncycles_per_iteration=100,populations=10,binary_operators=[\"+\", \"*\",\"/\"],
      2     unary_operators=[
      3         \"exp\",
      4         \"inv(x) = 1/x\",
      5         \"square\",
      6         \"cube\",
      7         \"sqrt\",
      8         \"log\",
      9         \"logistic(x) = 1 / (1 + exp(-x))\", 
     10         # ^ Custom operator (julia syntax)
     11     ],
---> 12     extra_sympy_mappings={\"inv\": lambda x: 1 / x,\"logistic\": lambda x: 1.0 / (1.0 + np.exp(-x))},)
     14 x = np.array([merged_df[\"N\"].values,merged_df[\"voltage\"].values]).T
     15 y = merged_df[\"P1\"].values*10

TypeError: loop of ufunc does not support argument 0 of type Mul which has no callable exp method"
}
```

**Comment by MilesCranmer** [comment]
It’s because `np.exp` is not a sympy function, it’s a numpy function

**Comment by SrGonao** [comment]
For some reason, I thought that using sympy.exp() had not worked. 
Trying it now and everything seems ok. ~
Thanks for the quick reply.

**Comment by SrGonao** [comment]
Sorry I remember why I used np.exp(). I'm still getting the error when having sympy.exp() and also get this extra warning:
``p1_fitting_no_ions.py:57: DeprecationWarning: scipy.exp is deprecated and will be removed in SciPy 2.0.0, use numpy.exp instead
  extra_sympy_mappings={"inv": lambda x: 1 / x,"logistic": lambda x: 1.0 / (1.0 + sp.exp(-x))},
ValueError: Error from parse_expr with transformed code: "(-Float ('0.68147457' )+logistic (x1 ))*x0 "

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "p1_fitting_no_ions.py", line 73, in <module>
    model.fit(x, y)
  File "/home/gpaulo/.local/lib/python3.8/site-packages/pysr/sr.py", line 1929, in fit
    self._run(X, y, mutated_params, weights=weights, seed=seed)
  File "/home/gpaulo/.local/lib/python3.8/site-packages/pysr/sr.py", line 1779, in _run
    self.equations_ = self.get_hof()
  File "/home/gpaulo/.local/lib/python3.8/site-packages/pysr/sr.py", line 2249, in get_hof
    eqn = pysr2sympy(
  File "/home/gpaulo/.local/lib/python3.8/site-packages/pysr/export_sympy.py", line 86, in pysr2sympy
    return sympify(equation, locals=local_sympy_mappings)
  File "/home/gpaulo/.local/lib/python3.8/site-packages/sympy/core/sympify.py", line 496, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/gpaulo/.local/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py", line 1101, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "/home/gpaulo/.local/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py", line 1092, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
  File "/home/gpaulo/.local/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py", line 907, in eval_expr
    expr = eval(
  File "<string>", line 1, in <module>
  File "p1_fitting_no_ions.py", line 57, in <lambda>
    extra_sympy_mappings={"inv": lambda x: 1 / x,"logistic": lambda x: 1.0 / (1.0 + sp.exp(-x))},
  File "/home/gpaulo/.local/lib/python3.8/site-packages/scipy/_lib/deprecation.py", line 20, in call
    return fun(*args, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type Mul which has no callable exp method
``

**Comment by MilesCranmer** [comment]
Are you calling scipy.exp? It should be sympy.exp. (The error message is from scipy it looks like)

**Comment by SrGonao** [comment]
Now that I'm reading the error it is strange that it does say scipy but I'm doing `import sympy as sp` and then sp.exp.

**Comment by SrGonao** [comment]
I'm sorry for wasting your time. I was indeed using scipy in this script. I had fixed it in other scripts but not this one.
